### ISSUE TITLE
GenBank files produced by Geseq cannot be imported into phylosuite

### ISSUE THREAD

**Issue by samyiu0109** [dongzhang0725/PhyloSuite#102]
![Screenshot 2024-10-10 134445](https://github.com/user-attachments/assets/a1e37089-61f7-4b22-93a0-888199af62c3)

The errors message
Traceback (most recent call last):
  File "Bio\SeqIO\InsdcIO.py", line 283, in _insdc_location_string
AttributeError: 'NoneType' object has no attribute 'parts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\handleGB.py", line 2089, in addRecordsSubFunc
  File "Bio\SeqIO\__init__.py", line 561, in write
  File "Bio\SeqIO\Interfaces.py", line 254, in write_file
  File "Bio\SeqIO\Interfaces.py", line 239, in write_records
  File "Bio\SeqIO\InsdcIO.py", line 1088, in write_record
  File "Bio\SeqIO\InsdcIO.py", line 399, in _write_feature
  File "Bio\SeqIO\InsdcIO.py", line 304, in _insdc_location_string
  File "Bio\SeqIO\InsdcIO.py", line 210, in _insdc_location_string_ignoring_strand_and_subfeatures
AttributeError: 'NoneType' object has no attribute 'ref'

GenBank file parse failed

**Comment by dongzhang0725** [comment]
genbank文件的注释不标准
