### ISSUE TITLE
安装mafft的时候出现的错误

### ISSUE THREAD

**Issue by han1511** [dongzhang0725/PhyloSuite#104]
Traceback (most recent call last):
  File "src\factory.py", line 588, in unZip
  File "zipfile.py", line 1507, in extract
  File "zipfile.py", line 1578, in _extract_member
PermissionError: [Errno 13] Permission denied: 'E:\\软件\\软件\\生物学软件\\PhyloSuite_v1.2.3_Win64\\PhyloSuite_v1.2.3_Win64\\PhyloSuite\\plugins\\mafft-win\\usr\\bin\\bash.exe'

**Comment by dongzhang0725** [comment]
mafft不是指定这个文件，见教程 http://phylosuite.jushengwu.com/dongzhang0725.github.io/PhyloSuite-demo/how-to-configure-plugins/
