### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by rolandfang** [dongzhang0725/PhyloSuite#16]
Traceback (most recent call last):
  File "codes\PhyloSuite.py", line 394, in run_command
  File "codes\PhyloSuite.py", line 277, in fetSeqFromNCBI
  File "site-packages\Bio\Entrez\__init__.py", line 184, in efetch
  File "site-packages\Bio\Entrez\__init__.py", line 533, in _open
  File "site-packages\Bio\Entrez\__init__.py", line 531, in _open
  File "urllib\request.py", line 223, in urlopen
  File "urllib\request.py", line 532, in open
  File "urllib\request.py", line 642, in http_response
  File "urllib\request.py", line 570, in error
  File "urllib\request.py", line 504, in _call_chain
  File "urllib\request.py", line 650, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by dongzhang0725** [comment]
Hi,

This problem is probably caused by the network malfunction, please check your network (proxy, etc.). An alternative option is using Batch Entrez (https://www.ncbi.nlm.nih.gov/sites/batchentrez?) to download the GenBank file, and then upload the file into PhyloSuite (see https://dongzhang0725.github.io/dongzhang0725.github.io/PhyloSuite-demo/five_ways_to_import/).

Best,
Dong
