### ISSUE TITLE
Bio.Alphabet Related

### ISSUE THREAD

**Issue by starsareintherose** [dongzhang0725/PhyloSuite#27]
```
░▒▓ ~/Dow/py/p/p/u/bin ▓▒░ ./PhyloSuite   ░▒▓ ✔  10:54:54 ▓▒░
Traceback (most recent call last):
  File "/home/guoyi/Downloads/py/pkg/phylosuite/usr/bin/./PhyloSuite", line 33, in <module>
    sys.exit(load_entry_point('PhyloSuite==1.2.2', 'console_scripts', 'PhyloSuite')())
  File "/home/guoyi/Downloads/py/pkg/phylosuite/usr/bin/./PhyloSuite", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/PhyloSuite/PhyloSuite.py", line 20, in <module>
    from src.main import MyMainWindow
  File "/usr/lib/python3.9/site-packages/PhyloSuite/src/main.py", line 23, in <module>
    from src.Lg_displaySettings import DisplaySettings
  File "/usr/lib/python3.9/site-packages/PhyloSuite/src/Lg_displaySettings.py", line 18, in <module>
    from src.handleGB import ArrayManager
  File "/usr/lib/python3.9/site-packages/PhyloSuite/src/handleGB.py", line 12, in <module>
    from Bio.Alphabet import generic_dna
  File "/usr/lib/python3.9/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

```

**Comment by dongzhang0725** [comment]
biopython 用1.71版本，python用3.6.7版本

月季花中的星辰 ***@***.***> 于2021年5月11日周二 上午10:58写道：
