### ISSUE TITLE
Concatenation 'Error'

### ISSUE THREAD

**Issue by kawu001** [dongzhang0725/PhyloSuite#31]
Traceback (most recent call last):
  File "codes\src\Lg_Concatenate.py", line 525, in run_command
  File "codes\src\Lg_Concatenate.py", line 126, in __init__
  File "codes\src\Lg_Concatenate.py", line 150, in concatenate
  File "codes\src\Lg_Concatenate.py", line 340, in save
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\PhyloSuite_v1.2.1_Win64_with_plugins\\myWorkPlace\\GenBank_File/files\\Flowchart_reports\\concatenate_results\\2021_07_08-20_39_50\\Curcuma AAL/BBT.fas'

**Comment by dongzhang0725** [comment]
I guess you set your export file name as "Curcuma AAL/BBT", among which "
/ " is not allowed, set your name as "Curcuma AAL_BBT" and try again.

Sincerely,

Dong

Bashir Bolaji TIAMIYU ***@***.***> 于2021年7月8日周四 下午8:41写道：
