### ISSUE TITLE
导入文件报错

### ISSUE THREAD

**Issue by awae876** [dongzhang0725/PhyloSuite#34]
Details:
Traceback (most recent call last):
  File "codes\src\handleGB.py", line 1750, in addRecordsSubFunc
  File "site-packages\Bio\SeqIO\__init__.py", line 517, in write
  File "site-packages\Bio\SeqIO\Interfaces.py", line 237, in write_file
  File "site-packages\Bio\SeqIO\Interfaces.py", line 222, in write_records
  File "site-packages\Bio\SeqIO\InsdcIO.py", line 815, in write_record
  File "site-packages\Bio\SeqIO\InsdcIO.py", line 624, in _write_the_first_line
ValueError: Need a Nucleotide or Protein alphabet

GenBank file parse failed
注释的gb文件导入报错："GenBank file parse failed, please check your file carefully!"，请问老师是什么问题，谢谢！

**Comment by 13399810274** [comment]
我也遇到了相同的问题，不是注释文件的问题，之前能导进去的数据，现在导不进去了，好像是我再手动添加数据分类信息的时候弹出来了错误，如何解决呢

**Comment by dongzhang0725** [comment]
一般是genebank的格式不标准，你和能导入的对比一下看看。实在不行可以发给我看看。

13399810274 ***@***.***> 于2021年12月1日周三 下午10:03写道：

**Comment by 13399810274** [comment]
非常感谢作者了，我解决了，原因是我在files界面手动补全的物种名的时候，空格有问题，导出excel的时候，里面显示的乱码，把乱码部分改了就好了
