### ISSUE TITLE
运行MAFFT遇到encountered an unforeseen problem

### ISSUE THREAD

**Issue by suanhaijiao** [dongzhang0725/PhyloSuite#47]
老师您好！ 我在运行MAFFT的时候遇到如下报错 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "codes\src\Lg_mafft.py", line 394, in run_command
  File "codes\src\Lg_mafft.py", line 470, in align
  File "codes\src\Lg_mafft.py", line 52, in __init__
  File "codes\src\Lg_mafft.py", line 107, in translate
  File "site-packages\Bio\Seq.py", line 2605, in _translate_str
Bio.Data.CodonTable.TranslationError: Codon 'TA.' is invalid

感谢您的帮助！

**Comment by dongzhang0725** [comment]
你好像是用的密码子比对模式，报错是说你的序列不是密码子序列，可能不是3的倍数，你先检查好开放阅读框再比对。

suanhaijiao ***@***.***> 于2022年2月24日周四 19:27写道：

**Comment by suanhaijiao** [comment]
非常感谢！！！
