### ISSUE TITLE
序列文件导入后，提取报错

### ISSUE THREAD

**Issue by baiyun13p** [dongzhang0725/PhyloSuite#48]
Traceback (most recent call last):
  File "codes\src\main.py", line 1073, in on_Extract_triggered
  File "codes\src\Lg_extracter.py", line 97, in __init__
  File "codes\src\Lg_extracter.py", line 474, in guiRestore
  File "codes\src\Lg_extracter.py", line 728, in displaySettings
  File "codes\src\Lg_extracter.py", line 739, in switchSeqType
AttributeError: 'ExtractGB' object has no attribute 'allVersions'

**Comment by dongzhang0725** [comment]
你是不是错删了设置文件，你再设置功能里面恢复默认设置试试看
