### ISSUE TITLE
MrBayes运行报错

### ISSUE THREAD

**Issue by Iris9310** [dongzhang0725/PhyloSuite#49]
老师您好 
       我在运行Mrbayes的时候 提示如下错误，是有什么问题吗？谢谢

Traceback (most recent call last):
  File "codes\src\Lg_Mrbayes.py", line 1458, in popupAutoDecSub
  File "codes\src\Lg_Mrbayes.py", line 1433, in workflow_input
  File "codes\src\factory.py", line 3296, in exec_
  File "codes\src\factory.py", line 3137, in readfile
AttributeError: 'NoneType' object has no attribute 'group'

另外 在运行完 modelfider后，将结果import用于MrBayes 会发生报错，并闪退 点不开detail，谢谢您！

**Comment by Iris9310** [comment]
尊敬的张老师：
       您好！
       首先感谢您的及时回复！我再次进行了尝试，有所突破！
       首先，我导入了nex格式在modelfider，发现input到贝叶斯时报错，发现data block文件中的matrix为空。
       随后，我就尝试导入phy格式，modelfider后，成功导入贝叶斯，也已成功运行！
       之前首次安装后，可能由于环境有冲突，也尝试过导入phy，但没有成功，在收到您邮件后，我重新进行了尝试，已解决问题！
       感谢您设计分析平台，为我们的数据分析带来极大的便利，同时感谢您为平台的维护以及答疑解惑！
       祝您工作顺心，科研顺利！


       叶润泽



--


叶润泽
山东大学公共卫生学院流行病与卫生统计学系
山东省济南市历下区文化西路44号 
微生物流行病学研究所
北京市丰台区丰台东大街20号院
邮编：250012
手机：+(86) 15698008707
***@***.***
Run-Ze Ye
Department of Epidemiology & Biostatistics
School of Public Health, Shandong University
No.44, Wenhuaxi Rd, Lixia Dist.
Jinan, 250012, P.R.C
Beijing Institute of Microbiology and Epidemiology
No.20, Dongdajie, Fengtai, Beijing 100071 China
Mobile: +(86) 15698008707
Email: ***@***.***













在 2022-03-18 22:15:23，"zhang dong" ***@***.***> 写道：

可能是自动导入mrbayes的文件格式不合适，你对比一下example里面能自动导入的和不能自动导入的有什么区别。如果还是不行可以把modelfinder的结果分享给我调试

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
