### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Sunch12** [dongzhang0725/PhyloSuite#52]
Traceback (most recent call last):
  File "codes\src\Lg_Mrbayes.py", line 558, in run_command
  File "codes\src\Lg_Mrbayes.py", line 1718, in summary
  File "f:\zd\python367\lib\codecs.py", line 321, in decode
MemoryError

**Comment by dongzhang0725** [comment]
试试新版本，修复了这个问题
