### ISSUE TITLE
GenBank file parse failed, please check your file carefully!

### ISSUE THREAD

**Issue by zzzzzhaozhuang** [dongzhang0725/PhyloSuite#54]
搜索NCBI导入gb文件时显示GenBank file parse failed, please check your file carefully!
报错信息如下：
"Traceback (most recent call last):
  File "codes\src\handleGB.py", line 1648, in prepareGB
  File "codes\src\handleGB.py", line 1183, in fetchAllIndex
  File "codes\src\handleGB.py", line 1029, in merge_gbIndex
  File "site-packages\Bio\File.py", line 394, in __getitem__
  File "site-packages\Bio\SeqIO\_index.py", line 69, in get
  File "site-packages\Bio\_py3k\__init__.py", line 61, in <lambda>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 1372: invalid continuation byte

GenBank file parse failed"

**Comment by dongzhang0725** [comment]
Please check your GenBank file carefully, better to make a standard GenBank file and try again.

**Comment by zzzzzhaozhuang** [comment]
邮件已收到，谢谢！                                                  ——赵荘

**Comment by YuanHuanyh** [comment]
> 搜索NCBI导入gb文件时显示GenBank file parse failed, please check your file carefully! 报错信息如下： "Traceback (most recent call last): File "codes\src\handleGB.py", line 1648, in prepareGB File "codes\src\handleGB.py", line 1183, in fetchAllIndex File "codes\src\handleGB.py", line 1029, in merge_gbIndex File "site-packages\Bio\File.py", line 394, in **getitem** File "site-packages\Bio\SeqIO_index.py", line 69, in get File "site-packages\Bio_py3k__init__.py", line 61, in UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 1372: invalid continuation byte
> 
> GenBank file parse failed"

请问怎么解决这个问题呀？

**Comment by zzzzzhaozhuang** [comment]
邮件已收到，谢谢！                                                  ——赵荘

**Comment by zzzzzhaozhuang** [comment]
邮件已收到，谢谢！                                                  ——赵荘
