### ISSUE TITLE
使用MAFFT时遇到问题

### ISSUE THREAD

**Issue by Jasemineyouzi** [dongzhang0725/PhyloSuite#55]
老师您好！在使用MAFFT时出现了报错，我的是蛋白序列，选择了codon模式
问题如下
Traceback (most recent call last):
  File "site-packages\Bio\Seq.py", line 2588, in _translate_str
  File "site-packages\Bio\Data\CodonTable.py", line 385, in __getitem__
KeyError: 'QQA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "codes\src\Lg_mafft.py", line 394, in run_command
  File "codes\src\Lg_mafft.py", line 470, in align
  File "codes\src\Lg_mafft.py", line 52, in __init__
  File "codes\src\Lg_mafft.py", line 105, in translate
  File "codes\src\Lg_mafft.py", line 91, in trim_ter
  File "site-packages\Bio\Seq.py", line 2605, in _translate_str
Bio.Data.CodonTable.TranslationError: Codon 'QQA' is invalid

**Comment by dongzhang0725** [comment]
你的序列里面有 QQA，这个不是标准的密码子序列，需要先调整一下序列

Jasemineyouzi ***@***.***> 于2022年12月21日周三 22:22写道：
