### ISSUE TITLE
mafft with unforeseen problem

### ISSUE THREAD

**Issue by doranicole1990** [dongzhang0725/PhyloSuite#60]
I try to mafft 13 PCGs of 29 species, The following error is always reported:
Traceback (most recent call last):
  File "src\Lg_mafft.py", line 418, in run_command
  File "src\Lg_mafft.py", line 540, in align
  File "src\Lg_mafft.py", line 173, in back_trans
  File "src\Lg_mafft.py", line 154, in tocodon
KeyError: '>K17_Diaulinopsis_sp__ATAATTTATTTGTTTATAATTTTTGATTCTTTTATTGTAATTATTGAAATAATTTTAATGGTTTTAATTTCTGTAGCTTTTTTAACTTTGTTAGAACGAAAAATTTTAGGGTATATTCAAATTCGTAAGGGTCCAAATAAAGTTGGATTTATGGGTTTACTTCAACCTTTTTCTGATGCAATTAAATTATTTAGAAAAGAAAATATAATAGTTTTAAAATCTAATTATTTTTT\n'
this is ND1 sequence with 954 length(ATA...TAG)， I don't really know where is the problem? please help me.

**Comment by dongzhang0725** [comment]
your fasta file is not in standard format, there should have a line break between sequence name and sequence.
