### ISSUE TITLE
序列提取时发生了这个错误是怎么回事

### ISSUE THREAD

**Issue by rshh98** [dongzhang0725/PhyloSuite#63]
Traceback (most recent call last):
  File "src\handleGB.py", line 2748, in _exec
  File "src\handleGB.py", line 4043, in saveGeneralFile
  File "src\handleGB.py", line 1034, in align_order
TypeError: 'NoneType' object is not iterable

**Comment by dongzhang0725** [comment]
检查一下你的序列是不是注释有问题。或者用例子文件跑一下看看能不能正常提取

rshh98 ***@***.***> 于2023年3月24日周五 10:41写道：
