### ISSUE TITLE
执行 MACSE 优化时出现此错误的原因是什么？谢谢。

### ISSUE THREAD

**Issue by yuanzhang1425** [dongzhang0725/PhyloSuite#66]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "multiprocessing\pool.py", line 119, in worker
  File "src\Lg_macse.py", line 60, in run
  File "subprocess.py", line 709, in __init__
  File "subprocess.py", line 997, in _execute_child
OSError: [WinError 740] 请求的操作需要提升。
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src\Lg_macse.py", line 363, in run_command
  File "src\Lg_macse.py", line 363, in <listcomp>
  File "multiprocessing\pool.py", line 670, in get
OSError: [WinError 740] 请求的操作需要提升。

**Comment by dongzhang0725** [comment]
phylosuite的安装路径以及工作区路径是否有中文或其它特殊字符。

**Comment by yuanzhang1425** [comment]
老师，您好，没有中文或其他特殊字符。

**Comment by dongzhang0725** [comment]
试试用管理员权限执行PhyloSuite，或者把PhyloSuite安装到一个有用户权限的文件夹。

**Comment by yuanzhang1425** [comment]
好的，谢谢老师。
