### ISSUE TITLE
Mrbayes error

### ISSUE THREAD

**Issue by CXna1108** [dongzhang0725/PhyloSuite#71]
老师，关于以下存储空间不足和字符报错一般怎么解决？
Division 1 has 708 unique site patterns
      Initializing conditional likelihoods
      Using standard non-SSE likelihood calculator for division 1 (single-precision)
      Out of memory. Most probable cause for the problem is that MrBayes reached 
      the limit of allowed memory for a process in your Operating System. Consult
      the documentation of your OS on how to extend the limit.                   
      Segmentation fault may follow.                                             
      Error in command "Mcmc"
      The error occurred when reading char. 5-5 on line 1149122
         in the file 'input.nex'

**Comment by dongzhang0725** [comment]
1. 确认是不是用的最新版（1.2.3）的phylosuite
2. 如果是最新版，换一个内存更大的电脑续跑试试

Chenxiaona ***@***.***> 于2023年5月12日周五 20:06写道：

**Comment by Aria-47** [comment]
老师，想问一下合并序列import to bayes之后显示Traceback (most recent call last):
  File "PhyloSuite/src/CustomWidget.py", line 702, in columnCount
IndexError: list index out of range是怎么回事啊

**Comment by dongzhang0725** [comment]
合并序列是什么意思？串联吗。还有，你是不是按教程来操作的，可以看下我们最新发表的protocol：
https://mp.weixin.qq.com/s/my1tp_OY6iy2USPbqoJ3VQ

Aria-47 ***@***.***> 于2024年7月24日周三 15:07写道：

**Comment by Aria-47** [comment]
合并序列是指两个基因联合建树，两个基因合并后的序列。我们选择的最适模型并没有得到想要的结果，想自定义模型重新试一下，但直接将序列导入Bayes分析后发现出现了报错
Traceback (most recent call last):

File "PhyloSuite/src/CustomWidget.py", line 702, in columnCount

IndexError: list index out of range




| |
王思琦
|
|
***@***.***
|


---- Replied Message ----
| From | zhang ***@***.***> |
| Date | 07/25/2024 08:04 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [dongzhang0725/PhyloSuite] Mrbayes error (Issue #71) |

合并序列是什么意思？串联吗。还有，你是不是按教程来操作的，可以看下我们最新发表的protocol：
https://mp.weixin.qq.com/s/my1tp_OY6iy2USPbqoJ3VQ

Aria-47 ***@***.***> 于2024年7月24日周三 15:07写道：
