### ISSUE TITLE
The program encountered an unforeseen problem

### ISSUE THREAD

**Issue by YuanHuanyh** [dongzhang0725/PhyloSuite#76]
When I concatenate the alignments into the PCGs12RNA dataset, check the “Split codon” checkbox, and check both the “first codon site” and “second codon site” checkboxes ,this error appeared. PhyloSuite_v1.2.3 is I used

**Comment by YuanHuanyh** [comment]
Traceback (most recent call last):
  File "src\Lg_Concatenate.py", line 572, in run_command
  File "src\Lg_Concatenate.py", line 133, in __init__
  File "src\Lg_Concatenate.py", line 148, in concatenate
  File "src\Lg_Concatenate.py", line 225, in append
KeyError: 'ATP6_CDS_NT_removed_chars'
