### ISSUE TITLE
“lmport to MACSE (for CDs)”点击“start”后出现错误

### ISSUE THREAD

**Issue by Guoxiaoting1** [dongzhang0725/PhyloSuite#77]
张老师：
您好！我在“lmport to MACSE (for CDs)”点击“start”后出现以下错误，请问该怎么处理呢？谢谢！
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "multiprocessing\pool.py", line 119, in worker
  File "src\Lg_macse.py", line 60, in run
  File "subprocess.py", line 709, in __init__
  File "subprocess.py", line 997, in _execute_child
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src\Lg_macse.py", line 363, in run_command
  File "src\Lg_macse.py", line 363, in <listcomp>
  File "multiprocessing\pool.py", line 670, in get
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by dongzhang0725** [comment]
检查路径中是否有中文，还有可以试试以管理员权限运行。

**Comment by Guoxiaoting1** [comment]
好的，非常感谢张老师！



2819271701
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dongzhang0725/PhyloSuite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月13日(星期二) 下午2:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dongzhang0725/PhyloSuite] “lmport to MACSE (for CDs)”点击“start”后出现错误 (Issue #77)





 
检查路径中是否有中文，还有可以试试以管理员权限运行。
