### ISSUE TITLE
运行显示错误，无法提取序列？

### ISSUE THREAD

**Issue by ffccff** [dongzhang0725/PhyloSuite#85]
Traceback (most recent call last):
  File "src\handleGB.py", line 2748, in _exec
  File "src\handleGB.py", line 4043, in saveGeneralFile
  File "src\handleGB.py", line 1034, in align_order
TypeError: 'NoneType' object is not iterable
分析质粒，但无法正常提取序列，遇到以上解释？

**Comment by dongzhang0725** [comment]
试试例子文件里面的genbank文件是否可以跑，如果可以，那你的序列的注释可能有问题，对照检查一下

ffccff ***@***.***> 于2023年11月9日周四 15:25写道：

**Comment by SYY09** [comment]
Traceback (most recent call last):
  File "codes\src\main.py", line 2745, in popFunction
  File "codes\src\main.py", line 1073, in on_Extract_triggered
  File "codes\src\Lg_extracter.py", line 97, in __init__
  File "codes\src\Lg_extracter.py", line 474, in guiRestore
  File "codes\src\Lg_extracter.py", line 728, in displaySettings
  File "codes\src\Lg_extracter.py", line 739, in switchSeqType
AttributeError: 'ExtractGB' object has no attribute 'allVersions'
提取线粒体基因组序列，无法提取。请问这是什么原因，感谢！

**Comment by dongzhang0725** [comment]
你可能动了phylosuite的一些设置文件，试试重新下载phylosuite看看能不能正常提取

SYY09 ***@***.***> 于2024年3月19日周二 00:30写道：
