### ISSUE TITLE
MrBayes Error

### ISSUE THREAD

**Issue by Zenobia2000** [dongzhang0725/PhyloSuite#88]
MrBayes stopped abnormally. Click Show log to see detail! You may copy the command (D:\PhyloSuite_v1.2.3_Win64_with_plugins\PhyloSuite_v1.2.3_Win64_with_plugins\PhyloSuite\plugins\MrBayes-3.2.7-WIN/bin/mb.3.2.7-win64.exe) to the terminal to debug it. For details, please visit [here](https://dongzhang0725.github.io/dongzhang0725.github.io/documentation/#7-3-MrBayes-does-not-work).

**Comment by dongzhang0725** [comment]
Please follow https://dongzhang0725.github.io/documentation/#7-3-MrBayes-does-not-work to try to fix this problem.

**Comment by Starryunivers** [comment]
The program encountered an unforeseen problem, please report the bug at https://github.com/dongzhang0725/PhyloSuite/issues or send an email with the detailed traceback to dongzhang0725@gmail.com
Traceback (most recent call last):
  File "src\Lg_Mrbayes.py", line 328, in on_pushButton_clicked
  File "src\Lg_Mrbayes.py", line 1328, in sumCmdBlock
AttributeError: 'MrBayes' object has no attribute 'seq_type'

**Comment by Starryunivers** [comment]
The program encountered an unforeseen problem, please report the bug at https://github.com/dongzhang0725/PhyloSuite/issues or send an email with the detailed traceback to dongzhang0725@gmail.com
Traceback (most recent call last):
  File "src\CustomWidget.py", line 702, in columnCount
IndexError: list index out of range

**Comment by dongzhang0725** [comment]
Please try the example file first. If it works, there may be some problem
with your input file.

Starryunivers ***@***.***> 于2024年4月19日周五 10:39写道：

**Comment by Starryunivers** [comment]
Just when I click on this Mrbayes option, it will pop up the error message

**Comment by dongzhang0725** [comment]
You can try to create a new workplace, then try these operations again.

Starryunivers ***@***.***> 于2024年4月19日周五 13:48写道：
