### ISSUE TITLE
生成12PCGsN数据集时核基因报错

### ISSUE THREAD

**Issue by XuanZhang-Black** [dongzhang0725/PhyloSuite#90]
张老师你好！我在串联线粒体基因组和多个核基因时将线粒体基因组的蛋白编码基因标记为PCG只提取1，2位密码子，核基因不标记，出现一条核基因序列报错，但是取消标记生成PCGsN数据集时又能正常运行，单独串联核基因，不标记PCG，但是下面勾选了Split codon这条基因也会有同样报错，请问是什么原因？
Traceback (most recent call last):
  File "src\Lg_Concatenate.py", line 572, in run_command
  File "src\Lg_Concatenate.py", line 133, in __init__
  File "src\Lg_Concatenate.py", line 148, in concatenate
  File "src\Lg_Concatenate.py", line 225, in append
KeyError: 'EF_1a_genewise_mafft_NT_removed_chars_trimAl'

**Comment by dongzhang0725** [comment]
不介意的话，可以把你的序列发到 dongzhang0725@gmail.com 邮箱，我有空debug一下
